/**
 * SportSync - Terms of Service Page
 *
 * Full legal Terms of Service for the platform.
 */
import { Link } from "react-router-dom";
import Footer from "../components/Footer";
import { ROUTES } from "../constants";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground-base">
      <header className="border-b border-muted/20 py-4 px-6">
        <div className="max-w-3xl mx-auto flex items-center justify-between">
          <Link to={ROUTES.HOME} className="text-xl font-bold text-accent">SportSync</Link>
          <Link to={ROUTES.HOME} className="text-sm text-muted hover:text-foreground transition-colors">
            ← Back to Home
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-bold text-foreground mb-2">Terms of Service</h1>
        <p className="text-sm text-muted mb-8">Last updated: March 14, 2026</p>

        <div className="space-y-8 text-sm leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using SportSync ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service. SportSync reserves the right to modify these terms at any time. Continued use of the Service after changes constitutes acceptance of the new terms.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">2. Eligibility</h2>
            <p>You must be at least 18 years of age to create an account or use the Service. By registering, you represent and warrant that you meet this age requirement. SportSync reserves the right to verify your age and suspend or terminate accounts that do not meet this requirement.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">3. Account Registration</h2>
            <p>To access certain features, you must create an account with a valid email address and a secure password (minimum 8 characters). You may also register using a Google account. You are responsible for maintaining the confidentiality of your login credentials and for all activities that occur under your account. You agree to notify SportSync immediately of any unauthorized use of your account.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">4. Acceptable Use</h2>
            <p>You agree not to: (a) use the Service for any unlawful purpose; (b) attempt to gain unauthorized access to the Service or its related systems; (c) interfere with or disrupt the integrity or performance of the Service; (d) use automated means to access the Service without prior written permission; (e) scrape, data-mine, or harvest any content from the Service; (f) impersonate any person or entity.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">5. Sports Data and Predictions</h2>
            <p>Sports scores and game data displayed on SportSync are sourced from third-party providers and may experience delays or inaccuracies. Win probability predictions are generated by machine learning models and represent statistical estimates, not guaranteed outcomes. SportSync does not endorse or encourage gambling. Predictions are for informational and entertainment purposes only. You should not rely solely on SportSync data for any financial decisions.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">6. Intellectual Property</h2>
            <p>All content, features, and functionality of the Service, including but not limited to text, graphics, logos, and software, are owned by SportSync and are protected by copyright,  trademark, and other intellectual property laws. Team logos and league names are trademarks of their respective owners and are used for identification purposes.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">7. Limitation of Liability</h2>
            <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, SPORTSYNC SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, OR USE, ARISING OUT OF OR IN CONNECTION WITH THE SERVICE. IN NO EVENT SHALL SPORTSYNC'S TOTAL LIABILITY EXCEED THE AMOUNT PAID BY YOU, IF ANY, FOR ACCESSING THE SERVICE DURING THE 12 MONTHS PRECEDING THE CLAIM.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">8. Indemnification</h2>
            <p>You agree to indemnify, defend, and hold harmless SportSync and its officers, directors, employees, and agents from and against any claims, liabilities, damages, losses, and expenses arising out of or in any way connected with your access to or use of the Service or your violation of these Terms.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">9. Termination</h2>
            <p>SportSync may suspend or terminate your account at its sole discretion, without notice, for conduct that it determines violates these Terms or is harmful to the Service, other users, or third parties. Upon termination, your right to use the Service will immediately cease. You may delete your account at any time through the Settings page.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">10. Governing Law</h2>
            <p>These Terms shall be governed by and construed in accordance with the laws of the State of New York, United States, without regard to its conflict of law provisions. Any disputes arising from these Terms shall be resolved exclusively in the state or federal courts located in New York County, New York.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">11. Contact</h2>
            <p>If you have any questions about these Terms of Service, please contact us at legal@sportsync.app.</p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
